### ISSUE TITLE
Clone of 'git@github.com:magnars/dash.el.git' into submodule path 'libs/dash' failed

### ISSUE THREAD

**Issue by bcoutre** [azer/emacs#12]
Hello, 
while trying doing the make, I got the following issue after asking the the 

`make
Initializing submodules
Cloning into 'libs/dash'...
The authenticity of host 'github.com (192.30.252.123)' can't be established.
RSA key fingerprint is 16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added 'github.com,192.30.252.123' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
Clone of 'git@github.com:magnars/dash.el.git' into submodule path 'libs/dash' failed
`

Any ideas ?

**Comment by azer** [comment]
it should be fixed now

**Comment by bcoutre** [comment]
Hello, 
Just work fine as expected thank you a lot for reactivity ! 

Regards
